                                 -*- mode : restclient -*-

:host=http://localhost:9001


# The basic hello world.
GET :host/


#
GET :host/hello

#
GET :host/goodbye

#
GET :host/hello/there


#
POST :host/debug
Content-Type: application/x-www-form-urlencoded
foo=bar
blah=ok


#
POST :host/register-user/bob/12345

#
POST :host/register-user
Content-Type: application/x-www-form-urlencoded
name=bob&mobile=888222
#
#
GET :host/user/tiger

